version: "3.9"

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "${SERVER_PORT}:25565"
    environment:
      EULA: "TRUE"
      TZ: ${TZ:-}
      TYPE: ${TYPE:-} # https://github.com/itzg/docker-minecraft-server#server-types
      VERSION: ${VERSION:-} # https://feedback.minecraft.net/hc/en-us/sections/360001186971-Release-Changelogs
      DIFFICULTY: ${DIFFICULTY:-}
      SERVER_NAME: ${SERVER_NAME:-}
      ENABLE_WHITELIST: ${ENABLE_WHITELIST:-}
      WHITELIST: ${WHITELIST:-}
      OPS: ${OPS:-}
      SPAWN_PROTECTION: ${SPAWN_PROTECTION:-}
      VIEW_DISTANCE: ${VIEW_DISTANCE:-}
      SEED: ${SEED:-}
      MODE: ${MODE:-}
      PVP: ${PVP:-}
      LEVEL_TYPE: ${LEVEL_TYPE:-}
      GENERATOR_SETTINGS: ${GENERATOR_SETTINGS:-}
      ONLINE_MODE: ${ONLINE_MODE:-}
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./data:/data

